# Generated by Django 3.2.19 on 2023-06-13 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l'instance est active")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="Désigne si l'instance est supprimée")),
                ('name', models.CharField(blank=True, max_length=220, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Code')),
                ('prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Préfixe')),
                ('flag', models.URLField(blank=True, max_length=256, null=True, verbose_name='Drapeau')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
    ]
