# Generated by Django 3.2.19 on 2023-06-13 20:50

import apps.users.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Prénoms')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse mail')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autres')], max_length=10, verbose_name='Sexe')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('conf_num', models.CharField(max_length=128, verbose_name='Numéro de confirmation')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('is_active', models.BooleanField(default=False, help_text='Désigne si cet utilisateur doit être traité comme actif. Désélectionnez cette option au lieu de supprimer les comptes. ', verbose_name="Désigne si l'utilisateur est actif")),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('is_staff', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.country', verbose_name='Pays de résidence')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l'instance est active")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="Désigne si l'instance est supprimée")),
                ('type', models.CharField(choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT')], max_length=220, verbose_name='Type de la transaction')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('local_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifiant local')),
                ('amount', models.CharField(max_length=128, verbose_name='Montant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
            managers=[
                ('inheritance_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transaction')),
                ('status', models.CharField(choices=[('DEPOSIT_TRANSACTION_INITIALIZED', 'DEPOSIT_TRANSACTION_INITIALIZED'), ('DEPOSIT_TRANSACTION_PAID', 'DEPOSIT_TRANSACTION_PAID'), ('DEPOSIT_TRANSACTION_COMPLETED', 'DEPOSIT_TRANSACTION_COMPLETED')], default='DEPOSIT_TRANSACTION_INITIALIZED', max_length=256, verbose_name='Status de la transaction')),
                ('url', models.URLField(blank=True, max_length=25, verbose_name='Adresse de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
            bases=('users.transaction',),
            managers=[
                ('inheritance_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transaction')),
                ('way', models.CharField(max_length=220, verbose_name='Moyen Utilisé Pour la transaction')),
                ('status', models.CharField(choices=[('STATUS_CREATE', 'STATUS_CREATE'), ('STATUS_INITIALIZED', 'STATUS_INITIALIZED'), ('STATUS_FINISHED', 'STATUS_FINISHED'), ('STATUS_UPDATE', 'STATUS_UPDATE')], default='STATUS_CREATE', max_length=120)),
            ],
            options={
                'verbose_name': 'Paiement de Retrait',
                'verbose_name_plural': 'Paiements de Retraits',
            },
            bases=('users.transaction',),
            managers=[
                ('inheritance_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancialAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l'instance est active")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="Désigne si l'instance est supprimée")),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte financier',
                'verbose_name_plural': 'Comptes financiers',
            },
        ),
    ]
