# Generated by Django 3.2.19 on 2023-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Désigne si cet utilisateur doit être traité comme actif. Désélectionnez cette option au lieu de supprimer les comptes. ', verbose_name="Désigne si l'utilisateur est actif"),
        ),
    ]
