# Generated by Django 3.2.19 on 2023-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='status',
            field=models.CharField(choices=[('STATUS_CREATED', 'STATUS_CREATED'), ('STATUS_INITIALIZED', 'STATUS_INITIALIZED'), ('STATUS_FAILED', 'STATUS_FAILED'), ('STATUS_FINISHED', 'STATUS_FINISHED'), ('STATUS_UPDATED', 'STATUS_UPDATED')], default='STATUS_CREATED', max_length=120),
        ),
    ]
