# Generated by Django 3.2.19 on 2023-06-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_withdrawtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(choices=[('DEPOSIT_TRANSACTION_INITIALIZED', 'DEPOSIT_TRANSACTION_INITIALIZED'), ('DEPOSIT_TRANSACTION_PAID', 'DEPOSIT_TRANSACTION_PAID'), ('DEPOSIT_TRANSACTION_FAILED', 'DEPOSIT_TRANSACTION_FAILED'), ('DEPOSIT_TRANSACTION_COMPLETED', 'DEPOSIT_TRANSACTION_COMPLETED')], default='DEPOSIT_TRANSACTION_INITIALIZED', max_length=256, verbose_name='Status de la transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant'),
        ),
    ]
