# Generated by Django 3.2.19 on 2023-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20230615_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bethistory',
            name='bet_data',
            field=models.JSONField(blank=True, default={'id': '', 'name': '', 'value': {'handicap': '', 'odd': '', 'value': ''}}, null=True, verbose_name='Informations de Paris'),
        ),
        migrations.AlterField(
            model_name='bethistory',
            name='bet_id',
            field=models.CharField(max_length=128, verbose_name='Identifiant du type de paris'),
        ),
        migrations.AlterField(
            model_name='bethistory',
            name='competition_id',
            field=models.CharField(max_length=128, verbose_name='Identifiant de la competition'),
        ),
        migrations.AlterField(
            model_name='bethistory',
            name='fixture_id',
            field=models.CharField(max_length=128, verbose_name='Identifiant du match'),
        ),
        migrations.AlterField(
            model_name='bethistory',
            name='status',
            field=models.CharField(choices=[('BET_STATUS_CREATED', 'BET_STATUS_CREATED'), ('BET_STATUS_INITIALIZED', 'BET_STATUS_INITIALIZED'), ('BET_STATUS_PROCESSED', 'BET_STATUS_PROCESSED')], default='BET_STATUS_CREATED', max_length=128, verbose_name='Status'),
        ),
    ]
