# Generated by Django 3.2.19 on 2023-06-17 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_bethistorychecker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetHistoryViewer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l'instance est active")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="Désigne si l'instance est supprimée")),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.bethistory', verbose_name='Viewer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
