# Generated by Django 3.2.19 on 2023-06-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_bethistoryviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bethistoryviewer',
            name='viewer',
        ),
        migrations.DeleteModel(
            name='BetHistoryChecker',
        ),
        migrations.DeleteModel(
            name='BetHistoryViewer',
        ),
    ]
